spring:
  application:
    name: shop-acc

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ShopAcc;encrypt=false;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  web:
    resources:
      cache:
        cachecontrol:
          no-store: true
          max-age: 0

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    open-in-view: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.shopacc.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-binding-errors: always

# ✅ THÊM JWT CONFIGURATION
jwt:
  secret: ShopAccSuperSecretKeyForJWTTokenGenerationMustBeLongEnoughAtLeast256BitsForHS256Algorithm
  expiration: 86400000      # 24 hours (in milliseconds)
  refresh-expiration: 604800000  # 7 days (in milliseconds)

# Logging Configuration
logging:
  level:
    root: INFO
    com.shopacc: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"